// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * Utilities for detecting auto-generated APIM resource IDs.
 *
 * APIM auto-generates 24-character lowercase hex IDs for certain resources:
 * - ApiSchema: when importing OpenAPI/WSDL specs, schemas get auto-generated IDs
 * - NamedValue: logger credentials (e.g., EventHub connection strings)
 *
 * These auto-generated resources should typically be skipped during publish
 * because APIM recreates them when the parent resource is published.
 */

/**
 * Pattern matching auto-generated 24-character lowercase hex IDs that APIM creates.
 * Examples: "69f15c3c10a45d29d855583a", "69f16ad1ee7da61d543198f7"
 */
const AUTO_GENERATED_ID_PATTERN = /^[0-9a-f]{24}$/;

/**
 * Pattern matching epoch-milliseconds schema IDs (Date.now()-style). The Azure
 * portal generates these client-side when a definition is added to an API that
 * has no schema resource yet (operation Frontend editor → "New definition").
 * Verified: ARM spec import generates 24-hex IDs on every api-version
 * 2021-08-01 … 2025-09-01-preview, so 13-digit IDs never come from import.
 * Example: "1786466527403"
 */
const PORTAL_SCHEMA_ID_PATTERN = /^\d{13}$/;

/**
 * Checks if a resource name/ID is an auto-generated 24-character hex ID.
 *
 * APIM auto-generates these IDs for:
 * - ApiSchema resources when importing OpenAPI/WSDL specifications
 * - NamedValue resources for logger credentials (EventHub, etc.)
 *
 * @param name - The resource name or ID to check
 * @returns true if the name matches the auto-generated pattern
 *
 * @example
 * isAutoGeneratedId('69f15c3c10a45d29d855583a') // true
 * isAutoGeneratedId('src-rest-schema-item')      // false
 * isAutoGeneratedId('my-named-value')            // false
 */
export function isAutoGeneratedId(name: string): boolean {
  return AUTO_GENERATED_ID_PATTERN.test(name);
}

/**
 * Checks if a schema name is a portal-generated 13-digit epoch-millis ID.
 *
 * Deliberately separate from isAutoGeneratedId: a 13-digit name is a weaker
 * heuristic than 24-hex, so it must only be applied where a false positive is
 * harmless — skipping ApiSchema re-publish when a spec import recreates the
 * schema content anyway. It must NOT gate named values, subscriptions, or
 * operations, where a silently skipped resource would lose data.
 *
 * @example
 * isPortalGeneratedSchemaId('1786466527403')  // true
 * isPortalGeneratedSchemaId('178646652740')   // false (12 digits)
 * isPortalGeneratedSchemaId('my-schema')      // false
 */
export function isPortalGeneratedSchemaId(name: string): boolean {
  return PORTAL_SCHEMA_ID_PATTERN.test(name);
}
