// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
/**
 * Utilities for detecting auto-generated APIM resource IDs.
 *
 * APIM auto-generates 24-character lowercase hex IDs for certain resources:
 * - ApiSchema: when importing OpenAPI/WSDL specs, schemas get auto-generated IDs
 * - NamedValue: logger credentials (e.g., EventHub connection strings)
 *
 * These auto-generated resources should typically be skipped during publish
 * because APIM recreates them when the parent resource is published.
 */

/**
 * Pattern matching auto-generated 24-character lowercase hex IDs that APIM creates.
 * Examples: "69f15c3c10a45d29d855583a", "69f16ad1ee7da61d543198f7"
 */
const AUTO_GENERATED_ID_PATTERN = /^[0-9a-f]{24}$/;

/**
 * Pattern matching the newer epoch-milliseconds schema IDs that APIM assigns
 * on spec import with recent API versions (e.g. 2025-09-01-preview).
 * Example: "1786466527403"
 */
const AUTO_GENERATED_TIMESTAMP_ID_PATTERN = /^\d{13}$/;

/**
 * Checks if a resource name/ID is an auto-generated APIM ID.
 *
 * APIM auto-generates these IDs for:
 * - ApiSchema resources when importing OpenAPI/WSDL specifications
 *   (24-char hex, or 13-digit epoch-millis on newer API versions)
 * - NamedValue resources for logger credentials (EventHub, etc.)
 *
 * @param name - The resource name or ID to check
 * @returns true if the name matches an auto-generated pattern
 *
 * @example
 * isAutoGeneratedId('69f15c3c10a45d29d855583a') // true
 * isAutoGeneratedId('1786466527403')             // true
 * isAutoGeneratedId('src-rest-schema-item')      // false
 * isAutoGeneratedId('my-named-value')            // false
 */
export function isAutoGeneratedId(name: string): boolean {
  return (
    AUTO_GENERATED_ID_PATTERN.test(name) ||
    AUTO_GENERATED_TIMESTAMP_ID_PATTERN.test(name)
  );
}
