diagnostics:
  - name: applicationinsights
    properties:
      loggerId: "/subscriptions/8ed73338-8d94-4cdf-a286-604fd0acf798/resourceGroups/UK-Infrastructure/providers/Microsoft.ApiManagement/service/prod-apim-uk-01/loggers/apim-uk-appinsights"

loggers:
  - name: apim-uk-appinsights
    properties:
      resourceId: "/subscriptions/8ed73338-8d94-4cdf-a286-604fd0acf798/resourceGroups/UK-Infrastructure/providers/microsoft.insights/components/APIM-UK-Prod-AppInsights"

apis:
  - name: swagger-petstore
    properties:
      serviceUrl: 'https://prod.petstore.swagger.io/v2'
      authenticationSettings:
        oAuth2: null
        openid: null
        oAuth2AuthenticationSettings: []
        openidAuthenticationSettings: []

  - name: webapitest
    properties:
      authenticationSettings:
        oAuth2: null
        openid: null
        oAuth2AuthenticationSettings: []
        openidAuthenticationSettings: []